import './globals.css'
import Navbar from './navbar/Navbar'
import Foot from './foot/Foot'

export const metadata = {
  title: 'Embassy Diplomat Screens by AIS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
     
      <Navbar />
        {children} 
      <Foot/>
      </body>
     
    </html>
  )
}
